### ISSUE TITLE
Not able to read from vault via spring cloud using profiles

### ISSUE THREAD

**Issue by joshisimt** [jandd/spring-boot-vault-demo#1]
Hi Team,

I have one microservice which get the config from vault via spring cloud.
It works fine without any profile. I need to fetch the details from vault on based of profile.
So I created folder structure in vault like `/secret/application/dev` and also `/secret/microservicename/dev` inside this I have all configurations.

So problem is I am unable to find it on profile basis from vault.
Can you please help?

Basic configuration for spring cloud server is as below-

`spring.profiles.active=vault,git
spring.cloud.config.server.vault.host=localhost
spring.cloud.config.server.vault.port=8900
spring.cloud.config.server.vault.order=1
spring.cloud.config.server.git.order=2
spring.cloud.config.server.git.uri=https://giturl
spring.cloud.config.server.git.username=username
spring.cloud.config.server.git.password=password
spring.cloud.config.server.git.searchPaths=configuration,iam
server.port=6565`

I have started the microservice in dev profile.

Thanks

**Comment by jandd** [comment]
@joshisimt maybe you should ask the spring cloud team on Stackoverflow? https://stackoverflow.com/questions/tagged/spring-cloud or is this related to this demo repository and I just do not see how?

**Comment by joshisimt** [comment]
Hi @jandd 
Thanks, I have created it there.
Sorry for creating it here.
